{
    "codecov": {
        "require_ci_to_pass": true, 
        "token": "c13baa18-8082-4795-a61b-96df024a5bf5"
    }, 
    "comment": {
        "behavior": "default", 
        "layout": "reach,diff,flags,tree", 
        "require_changes": false
    }, 
    "coverage": {
        "precision": 2, 
        "range": [
            70.0, 
            100.0
        ], 
        "round": "down"
    }, 
    "parsers": {
        "gcov": {
            "branch_detection": {
                "conditional": true, 
                "loop": true, 
                "macro": false, 
                "method": false
            }
        }
    }
}
